deploy:
  provider: pypi
  user: jonathanpallant
  password:
    secure: NZo7Hme7FBTBpXPcPu5cjDFOQPkvXyKfKuc9boOrxhkG6x1Z794M2nwWig/UmJHZ5hfBETkwGqjEDc9N6fHnO1WiSFVkfs1+TrWYWi4DZYNJc9HbXeVD+QtQd577l7Y5dXMxJIQkT1r7xqlPyCJ/zFR/XtgUfmk9Wxuwvl725Zjneh/yQF6Nl8q4qO6Tyc1K0JvNNyC8q7WqJJElWBYDqPRGtrf8KTlKYcyyPkMXrcPn5b6oMv4rF5932AqP1dLd3gd/udiduR6qNG6EcYm0lwRSVpeerCxYgFBRc+E4MKHAnYof93C4bmjuxlKheeqGahYp8/ZcgAcH1bM2YlrRr7jDl39tpT4Xt/wrnC2rnlA81bXCrfZXkr5UhBSxe4SxYbED1FCNPJj5GwPWgTHAjegj8kwx8486xXLlk4lAY5SuLUB0In+SPGbpmk2pcAy7Ufmu9uUXscdLK9/zfjVYECA9FCDYaXgu1PnXdL2a0RO0EHTZyNWpSEorHqV03AwwvoB1f+eSJVFdvTRPCqLqW4qRXAU9A9c0vYBsNBjNIM+e31p8zF3NuPxomafCj7xcfMQn+33hIsjS1pz+ZnxhyPM2ogdTSsCUU7EqPJW/nWpC2VyfIQKEclim3qcN2H75KxK07viITyBOpKKCzaYjnttb+xEd08+4b8ETPB8TC1U=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
