language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "pip install ."
  - "pip install nose"
script: nosetests --with-doctest
deploy:
  # production pypi
  #- provider: pypi
  #  user: "__token__"
  #  password:
  #    secure: "Djo5OsdaQpx/dXxN1Mmcdx6AZJfXIB5Ji40PpSdNj8k2bNQM4YKg3/lMk3lfZnZx5ZzZfUvwi6GQ5l18B+d+O+7xmDmaO0d57pQsk1N/QXQejEM6EvRC1sN/BVla/5hQAwkoZo5EfSRY5B9O4VaX/QmBt26+dcEk5P4e8Lc27TZ9xqFPKWwQRzutwv96Goz3LP3vosdgUcGqDrc9+IIiVZV40yWG69VZ+2u9b8aCrL0Husc0ZtidPOIoGwL+zxb1i49xGwxM23DDRBDZWCbRDMecIix77rcf1GjaA4zWRGdzSJA4umew7wwzENvvWUQLmkHImhRmy1l6SsRt6TIsNtAQ+yWpmTbKdaDGJNvw25mNAqs9LhxMtW/jrokpKXH6L1bql1hRKm2It+77gpCMiGxM093GCwVJCCx6vNtFGh0bcBG2Zcf7Phda+eN0G9fKz1C3XguHRNEuPY0zI1pxirDtGyO3R/85QDatY82fPr6xDMYz1NxavDG9RpbgrHf09YIpVh2mFAdMxIUvjWe74f8/TkJ8SVS5Lhsih4C3ohh7wA/+8ifxR1ZCfV6J1AlX5OF6+UTU9Kl5CbZ5+xbz0K/F5jkSqVf7tVuZDvwUBRGkAnWksIij6U0al7FI8WTvfauJeDVwX1Y8ZofGqJh3nA1ENJ6NCAi7i6sV+9k4idI="
  #  distributions: sdist bdist_wheel
  #  on:
   #   tags: true
   #   condition: $TRAVIS_PYTHON_VERSION = "3.9"
  # test pypi
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    user: jonathanpallant
    password:
      secure: NZo7Hme7FBTBpXPcPu5cjDFOQPkvXyKfKuc9boOrxhkG6x1Z794M2nwWig/UmJHZ5hfBETkwGqjEDc9N6fHnO1WiSFVkfs1+TrWYWi4DZYNJc9HbXeVD+QtQd577l7Y5dXMxJIQkT1r7xqlPyCJ/zFR/XtgUfmk9Wxuwvl725Zjneh/yQF6Nl8q4qO6Tyc1K0JvNNyC8q7WqJJElWBYDqPRGtrf8KTlKYcyyPkMXrcPn5b6oMv4rF5932AqP1dLd3gd/udiduR6qNG6EcYm0lwRSVpeerCxYgFBRc+E4MKHAnYof93C4bmjuxlKheeqGahYp8/ZcgAcH1bM2YlrRr7jDl39tpT4Xt/wrnC2rnlA81bXCrfZXkr5UhBSxe4SxYbED1FCNPJj5GwPWgTHAjegj8kwx8486xXLlk4lAY5SuLUB0In+SPGbpmk2pcAy7Ufmu9uUXscdLK9/zfjVYECA9FCDYaXgu1PnXdL2a0RO0EHTZyNWpSEorHqV03AwwvoB1f+eSJVFdvTRPCqLqW4qRXAU9A9c0vYBsNBjNIM+e31p8zF3NuPxomafCj7xcfMQn+33hIsjS1pz+ZnxhyPM2ogdTSsCUU7EqPJW/nWpC2VyfIQKEclim3qcN2H75KxK07viITyBOpKKCzaYjnttb+xEd08+4b8ETPB8TC1U=
    on:
      branch: python_ci_updates
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.9"
